# Generated by Django 3.1 on 2022-12-13 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_auto_20221213_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='fk_project',
            new_name='fk_organization',
        ),
    ]
